;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GE.Damage",NewTagName="GE.Damager")
+GameplayTagRedirects=(OldTagName="GunR.Weapon.MoveWeaponDamage",NewTagName="GunR.Weapon.MoreWeaponDamage")
+GameplayTagRedirects=(OldTagName="Jelly.AI.Perseption.FrogetTarget",NewTagName="Jelly.AI.Perseption.ForgetTarget")
+GameplayTagList=(Tag="Character.Dead",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.Weapon1",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.Weapon2",DevComment="")
+GameplayTagList=(Tag="Game.Difficulty.EnemyAmount",DevComment="")
+GameplayTagList=(Tag="GamePhase.Pawn.BlockInput",DevComment="")
+GameplayTagList=(Tag="GamePhase.Pawn.Reset",DevComment="")
+GameplayTagList=(Tag="GamePhase.State.Gaming",DevComment="")
+GameplayTagList=(Tag="GamePhase.State.PostGame",DevComment="")
+GameplayTagList=(Tag="GamePhase.State.PreGame",DevComment="")
+GameplayTagList=(Tag="GamePhase.State.WarmUp",DevComment="")
+GameplayTagList=(Tag="GameplayCue.CarExplosion",DevComment="")
+GameplayTagList=(Tag="GameplayCue.EndGame",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FireBreath",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FireDamage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Invisible",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Notification",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Reset",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Telekinetic",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Impact",DevComment="")
+GameplayTagList=(Tag="GE.Damager",DevComment="")
+GameplayTagList=(Tag="GunR.Block.BlockingMag",DevComment="")
+GameplayTagList=(Tag="GunR.Block.HealingBlock",DevComment="")
+GameplayTagList=(Tag="GunR.Block.Shield",DevComment="")
+GameplayTagList=(Tag="GunR.Character.Bloodthirst",DevComment="")
+GameplayTagList=(Tag="GunR.Character.Vampirism",DevComment="")
+GameplayTagList=(Tag="GunR.Weapon.AutoFire",DevComment="")
+GameplayTagList=(Tag="GunR.Weapon.ChainLightning",DevComment="")
+GameplayTagList=(Tag="GunR.Weapon.ChaoticBrain",DevComment="")
+GameplayTagList=(Tag="GunR.Weapon.FreezeBullets",DevComment="")
+GameplayTagList=(Tag="GunR.Weapon.MoreWeaponDamage",DevComment="")
+GameplayTagList=(Tag="GunR.Weapon.Shotgun",DevComment="")
+GameplayTagList=(Tag="GunR.Weapon.WindBullets",DevComment="")
+GameplayTagList=(Tag="InputTag.AutoFire",DevComment="")
+GameplayTagList=(Tag="InputTag.Fire",DevComment="")
+GameplayTagList=(Tag="InputTag.Jump",DevComment="")
+GameplayTagList=(Tag="InputTag.MRB",DevComment="")
+GameplayTagList=(Tag="InputTag.Reload",DevComment="")
+GameplayTagList=(Tag="InputTag.Sprint",DevComment="")
+GameplayTagList=(Tag="Inventory.Added",DevComment="")
+GameplayTagList=(Tag="Jelly",DevComment="")
+GameplayTagList=(Tag="Jelly.Ability.FireBreath",DevComment="")
+GameplayTagList=(Tag="Jelly.Ability.FireBreath.Cost",DevComment="")
+GameplayTagList=(Tag="Jelly.Ability.FireBreath.Damage",DevComment="")
+GameplayTagList=(Tag="Jelly.Ability.FireBreath.DOT",DevComment="")
+GameplayTagList=(Tag="Jelly.Ability.FireBreath.Restore",DevComment="")
+GameplayTagList=(Tag="Jelly.Ability.Movement",DevComment="")
+GameplayTagList=(Tag="Jelly.Ability.Scanning",DevComment="")
+GameplayTagList=(Tag="Jelly.Ability.Sprint.Cost",DevComment="")
+GameplayTagList=(Tag="Jelly.Ability.Sprint.Restore",DevComment="")
+GameplayTagList=(Tag="Jelly.Ability.Telekinetic",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Action",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Action.EndAbility",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Action.EndInteract",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Action.GetDamage",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Action.IniviseEnd",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Action.IniviseStart",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Action.Reload",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Action.StartInteract",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Action.TrashNoise",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.AIChangeState",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Control",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Control.BlockAi",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Effects",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Effects.CoolDown",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Encounter",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Encounter.Finished",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Encounter.SeeTarget",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Info.SeeCoolDown",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Mood.Angry",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Mood.Neutral",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Mood.Passive",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Movement",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Movement.Sitting",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Perseption",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Perseption.CanHear",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Perseption.CanSee",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Perseption.ForgetTarget",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Perseption.HearTarget",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Perseption.LoseTarget",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Perseption.SeeTarget",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Perseption.Sense",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.SmartObjects",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.SmartObjects.RuntimeTag",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.SmartObjects.RuntimeTag.Active",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.SmartObjects.RuntimeTag.CoolDown",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.SmartObjects.RuntimeTag.Uses",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.SmartObjects.Sofa",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.SmartObjects.Sofa.Left",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.SmartObjects.Sofa.Right",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.SmartObjects.Trap",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.State",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.State.Alert",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.State.Attacking",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.State.Chasing",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.State.Interacting",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.State.Searching",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.State.SetEnemy",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.State.SpiderSense",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.State.Waiting",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.State.Wandering",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.StateTree.InfoUpdate",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Users",DevComment="")
+GameplayTagList=(Tag="Jelly.AI.Users.OldMan",DevComment="")
+GameplayTagList=(Tag="Jelly.Effects",DevComment="")
+GameplayTagList=(Tag="Jelly.Effects.Death",DevComment="")
+GameplayTagList=(Tag="Jelly.Effects.Knock",DevComment="")
+GameplayTagList=(Tag="Jelly.Effects.LowGravity",DevComment="")
+GameplayTagList=(Tag="Jelly.Effects.MegaHead",DevComment="")
+GameplayTagList=(Tag="Jelly.Effects.MegaJump",DevComment="")
+GameplayTagList=(Tag="Jelly.Effects.QuestUpdate",DevComment="")
+GameplayTagList=(Tag="Jelly.Effects.Trap",DevComment="")
+GameplayTagList=(Tag="Jelly.Enemies.OldMan",DevComment="")
+GameplayTagList=(Tag="Jelly.Events",DevComment="")
+GameplayTagList=(Tag="Jelly.Events.ItemDelivered",DevComment="")
+GameplayTagList=(Tag="Jelly.Events.KnockTarget",DevComment="")
+GameplayTagList=(Tag="Jelly.Gadgets.Snap.Ammo",DevComment="")
+GameplayTagList=(Tag="Jelly.Input.AbiltyRight",DevComment="")
+GameplayTagList=(Tag="Jelly.Input.Invise",DevComment="")
+GameplayTagList=(Tag="Jelly.Items",DevComment="")
+GameplayTagList=(Tag="Jelly.Items.Apple",DevComment="")
+GameplayTagList=(Tag="Jelly.Items.CameraAmmo",DevComment="")
+GameplayTagList=(Tag="Jelly.Items.Destructable",DevComment="")
+GameplayTagList=(Tag="Jelly.Items.Kitchen",DevComment="")
+GameplayTagList=(Tag="Message.NewPlayer",DevComment="")
+GameplayTagList=(Tag="Player.Score.Deaths",DevComment="")
+GameplayTagList=(Tag="Player.Score.Kills",DevComment="")
+GameplayTagList=(Tag="UI.Anchor.BulletsTab",DevComment="")
+GameplayTagList=(Tag="UI.Anchor.Crosshair",DevComment="")
+GameplayTagList=(Tag="UI.Anchor.Elimination",DevComment="")
+GameplayTagList=(Tag="UI.Anchor.FullScreen",DevComment="")
+GameplayTagList=(Tag="UI.Anchor.GlobalNotification",DevComment="")
+GameplayTagList=(Tag="UI.Anchor.Help",DevComment="")
+GameplayTagList=(Tag="UI.Anchor.InfoBar",DevComment="")
+GameplayTagList=(Tag="UI.Anchor.PlayerInfo",DevComment="")
+GameplayTagList=(Tag="UI.Anchor.QuickBar",DevComment="")
+GameplayTagList=(Tag="UI.Anchor.Timer",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Game",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Tabs",DevComment="")
+GameplayTagList=(Tag="UI.Layer.UI",DevComment="")
+GameplayTagList=(Tag="Weapon.Projectile.Bouncy",DevComment="")
+GameplayTagList=(Tag="Weapon.Projectile.ExplosiveBullet",DevComment="")
+GameplayTagList=(Tag="Weapon.Ranged.AmmoCount",DevComment="")
+GameplayTagList=(Tag="Weapon.Ranged.BlockDefaultPistol",DevComment="")
+GameplayTagList=(Tag="Weapon.Ranged.DefaultPistol",DevComment="")
+GameplayTagList=(Tag="Weapon.Ranged.Reloading",DevComment="")

